sudo: false
language: node_js
node_js:
  - "7.6"
  - "7"
  - "8"
  - "9"
 matrix:
  allow_failures:
  - node_js: '9'
cache:
  directories:
    - node_modules
before_script:
  - npm install
script:
  - npm test
