version: "3"
services:
  wine-coolq:
    image: coolq/wine-coolq:latest
    container_name: coolq
    ports:
      - 21312:9000
    volumes:
      - ./coolq-data:/home/user/coolq;
    environment:
      - VNC_PASSWD
      - COOLQ_ACCOUNT
