name: "deploy website"

on:
  push:
    branches:
      - release
      - docs
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DOCDIR: ./services/Website/
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: NPM Cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles(format('{0}./package-lock.json', env.DOCDIR)) }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install deps
        run: cd ${{ env.DOCDIR }} && npm ci
      - name: Build
        run: cd ${{ env.DOCDIR }} && npm run build
      - name: Deploy
        uses: ngduc/vercel-deploy-action@master
        with:
          vercel-cli: vercel
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
          working-directory: ${{ env.DOCDIR }}
